name: Build and Package

on:
  push:
    branches:
      - br1
  pull_request:
    branches:
      - br1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: br1
      
    - name: Set up CMake
      uses: cmake/action-setup@v2
      
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Install
      run: make -C build install

    - name: Package with CPack
      run: cmake -DCPACK_PROJECT_NAME=MyProject -DCPACK_GENERATOR=ZIP --build build && cpack -G ZIP

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rk2-executable-br1
        path: RK2-1.0.0-Linux.zip

