name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: cmake/action-setup@v2
      
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Install
      run: make -C build install

    - name: Package with CPack
      run: cpack -G ZIP

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rk2-executable
        path: RK2_executable.zip

