name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Package with CPack
      run: cmake --install build --prefix install && cpack -G ZIP

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rk2-artifact
        path: install
