name: Build and Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Install
      run: make -C build install

    - name: Package with CPack
      run: cmake -DCPACK_PROJECT_NAME=MyProject -DCPACK_GENERATOR=ZIP --install build && cpack

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rk2-executable
        path: RK2-1.0.0-Linux.zip

