name: CPack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_packages_Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Config ConceptualExample
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/build -D PRINT_VERSION=1.0.0

      - name: Build ConceptualExample
        run: cmake --build ${{github.workspace}}/build

      - name: Build package
        run: cmake --build ${{github.workspace}}/build --target package

      - name: Build source package
        run: cmake --build ${{github.workspace}}/build --target package_source

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rk2-executable
          path: RK2-1.0.0-Linux.zip
      
      - name: Make a release
        uses: ncipollo/release-action@v1.11.0
        with:
          tag: v1.0.2
          artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
