name: CPack

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: cmake/action-setup@v2
      
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Install
      run: make -C build install

    - name: Package with CPack
      run: cmake -DCPACK_PROJECT_NAME=MyProject -DCPACK_GENERATOR=ZIP --build build && cpack -G ZIP

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rk2-executable
        path: RK2-1.0.0-Linux.zip

  create_release:
    needs: release
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: rk2-executable
        path: rk2-executable

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v1.0.0
        release_name: Release v1.0.0
        body: |
          This is the first release of the project.
        draft: false
        prerelease: false
        files: rk2-executable/*
