name: CPack

on:
  push:
    branches: [master]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [master]
    tags:
      - "v*.*.*"
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Configure
        run: cmake ${{github.workspace}} -B ${{github.workspace}}/.build/ -D PRINT_VERSION=1.2.0 -D PACK=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/.build/

      - name: Package
        run: |
          cd ${{github.workspace}}/.build/
          cpack

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{github.workspace}}/.build/*.deb

  create_tag_and_release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ${{github.workspace}}/.build/

      - name: Create a release
        uses: ncipollo/release-action@v1.11.0
        with:
          tag: v1.0.5
          replaceArtifacts: false
          artifacts: ${{github.workspace}}/.build/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
